import './globals.css'
import type {Metadata} from 'next'
import Auth0Provider from './auth0Provider'
import {Inter} from 'next/font/google'


const inter = Inter({subsets: ['latin']})


export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Auth0Provider>
            {children}
        </Auth0Provider>
        </body>
        </html>
    )
}
