import './globals.css'
import type {Metadata} from 'next'
import Auth0Provider from './auth0Provider'
import React from 'react';

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function RootLayout({children}: {
    children: React.ReactNode
}) {
    return (
        <html lang='en'>
        <body className='bg-stone-50 dark:bg-stone-900'>
        <Auth0Provider>
            {children}
        </Auth0Provider>
        </body>
        </html>
    )
}
