INSERT INTO public."Activity" (id, name, "categoryId") VALUES (1, 'Apoyo estudios académicos (grado académico)', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (2, 'Apoyo educación continua (cursos, bootcamps, certificaciones, diplomados, etc.)', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (3, 'Apoyo material escolar', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (4, 'Apoyo emprendedores', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (5, 'Apoyo cultural', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (6, 'Apoyo deportivo', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (7, 'Apoyo investigación', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (8, 'Apoyo alimentación', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (9, 'Apoyo movilidad (internacionalización)', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (10, 'Apoyo transporte', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (11, 'Apoyo alojamiento', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (12, 'Apoyo a fundaciones religiosas', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (13, 'Apoyo prácticas profesionales', 1);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (14, 'Protección, conservación, restauración y/o recuperación del patrimonio cultural de la nación', 2);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (15, 'Protección, conservación, restauración y/o recuperación del arte de las comunidades indígenas', 2);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (16, 'Promoción, fomento y difusión de actividades culturales, musicales y artísticas (clásicas, contemporaneas, mixtas, urbanas)', 2);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (17, 'Promoción, fomento y difusión de actividades deportivas', 2);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (18, 'Creación de empleo y desarrollo de la fuerza laboral', 3);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (19, 'Capacitación laboral', 3);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (20, 'Responsabilidad social corporativa', 3);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (21, 'Emprendimiento', 3);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (22, 'Cooperativas de ahorro y crédito', 3);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (23, 'Asesoramiento financiero', 3);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (24, 'Promoción y aportación de servicios para la salud', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (25, 'Programas de nutrición', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (26, 'Rehabilitación Juvenil', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (27, 'Rehabilitación Física', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (28, 'Atención Psicoterapéutica', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (29, 'Emergencias', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (30, 'Prevención de enfermedades', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (31, 'Adicciones', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (32, 'Servicios de comedor', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (33, 'Bancos de alimentos', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (34, 'Acceso a medicamentos', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (35, 'Ayuda al viajero', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (36, 'Ayuda a las víctimas', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (37, 'Banco de ropa', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (38, 'Organización comunitaria', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (39, 'Servicio a la comunidad', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (40, 'Asociaciones de vecinos', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (41, 'Adopción', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (42, 'Acogimiento', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (43, 'Servicios de empleo', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (44, 'Servicios o rehabilitación de vivienda', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (45, 'Alojamiento temporal', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (46, 'Servicios, atención y/o cuidados para inmigrantes', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (47, 'Servicios, atención y/o cuidados para la mujer', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (48, 'Servicios, atención y/o cuidados para jóvenes', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (49, 'Servicios, atención y/o cuidados a personas con discapacidad', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (50, 'Servicios, atención y/o cuidado de adultos mayores', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (51, 'Servicios, atención y/o cuidado de niños, niñas y adolescentes', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (52, 'Educación y formación en derechos humanos', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (53, 'Promoción de la equidad de género', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (54, 'Prevención de la violencia de género', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (55, 'Asistencia jurídica', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (56, 'Apoyo en la defensa y promoción de los derechos humanos para la reducción de las desigualdades', 4);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (57, 'Protección del medio ambiente', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (58, 'Preservación forestal', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (59, 'Manejo de especies invasoras', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (60, 'Protección de la fauna acuática', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (61, 'Protección de especies en peligro de extinción', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (62, 'Parques zoológicos', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (63, 'Adopciones, rescate y/o rehabilitación de animales', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (64, 'Cambio climático', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (65, 'Calidad del aire', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (66, 'Reciclaje y/o gestión de residuos peligrosos', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (67, 'Conservación y/o tratamiento del agua', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (68, 'Reproducción de especies en protección y peligro de extinción', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (69, 'Conservación de especies en peligro de extinción', 5);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (70, 'Formación y educación en apoyo a niños, adolescentes y jóvenes', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (71, 'Educación de adultos', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (72, 'Aprendizaje fuera de la escuela', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (73, 'Participación de padres y maestros', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (74, 'Promoción de la lectura', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (75, 'Tutoría', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (76, 'Educación para superdotados (alto rendimiento)', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (77, 'Educación STEM', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (78, 'Educación STEAM', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (79, 'Educación ambiental', 6);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (80, 'Promoción y fomento de la investigación en ciencias de la salud', 7);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (81, 'Promoción y fomento de la investigación en ingeniería y tecnología', 7);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (82, 'Promoción y fomento de la investigación en en ciencias naturales, de la Tierra y agropecuarias', 7);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (83, 'Promoción y fomento de la investigación en en ciencias exactas', 7);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (84, 'Promoción y fomento de la investigación en ciencias sociales', 7);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (85, 'Promoción y fomento de la investigación en ciencias administrativas', 7);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (86, 'Promoción y fomento de la investigación en humanidades', 7);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (87, 'Desarrollo orientado a ciclistas y peatones', 8);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (88, 'Desarrollo rural', 8);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (89, 'Transporte público', 8);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (90, 'Planificación urbana', 8);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (91, 'Bibliotecas públicas', 8);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (92, 'Bibliotecas privadas de acceso público', 8);
INSERT INTO public."Activity" (id, name, "categoryId") VALUES (93, 'Museos privados de acceso público', 8);
