INSERT INTO public."OrganizationCategory" (id, name) VALUES (1, 'Asamblea');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (2, 'Club');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (3, 'Colectivo');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (4, 'Congregación');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (5, 'Comité');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (6, 'Comunidad de aprendizaje');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (7, 'Gremio');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (8, 'Grupo de trabajo o agrupación');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (9, 'Iniciativa');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (10, 'Junta');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (11, 'Liga');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (12, 'Laboratorio ciudadano');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (13, 'Movimiento');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (14, 'Organización de la sociedad civil');
INSERT INTO public."OrganizationCategory" (id, name) VALUES (15, 'Red');
