INSERT INTO public."VolunteerCountCategory" (id, "minCount", "maxCount") VALUES (1, 0, 0);
INSERT INTO public."VolunteerCountCategory" (id, "minCount", "maxCount") VALUES (2, 1, 5);
INSERT INTO public."VolunteerCountCategory" (id, "minCount", "maxCount") VALUES (3, 6, 10);
INSERT INTO public."VolunteerCountCategory" (id, "minCount", "maxCount") VALUES (4, 11, 20);
INSERT INTO public."VolunteerCountCategory" (id, "minCount", "maxCount") VALUES (5, 21, 50);
INSERT INTO public."VolunteerCountCategory" (id, "minCount", "maxCount") VALUES (6, 51, 100);
INSERT INTO public."VolunteerCountCategory" (id, "minCount", "maxCount") VALUES (7, 101, 250);
INSERT INTO public."VolunteerCountCategory" (id, "minCount", "maxCount") VALUES (8, 251, 500);
INSERT INTO public."VolunteerCountCategory" (id, "minCount", "maxCount") VALUES (9, 501, null);
