insert into "AgeGroup"
values (default, 'female', 0, 5),
       (default, 'female', 6, 11),
       (default, 'female', 12, 14),
       (default, 'female', 15, 17),
       (default, 'female', 18, 26),
       (default, 'female', 27, 59),
       (default, 'female', 59, null),
       (default, 'male', 0, 5),
       (default, 'male', 6, 11),
       (default, 'male', 12, 14),
       (default, 'male', 15, 17),
       (default, 'male', 18, 26),
       (default, 'male', 27, 59),
       (default, 'male', 59, null),
       (default, null, 0, 5),
       (default, null, 6, 11),
       (default, null, 12, 14),
       (default, null, 15, 17),
       (default, null, 18, 26),
       (default, null, 27, 59),
       (default, null, 59, null);

