INSERT INTO public."Beneficiary" (id, name) VALUES (1, 'Familias');
INSERT INTO public."Beneficiary" (id, name) VALUES (2, 'Familias monoparentales');
INSERT INTO public."Beneficiary" (id, name) VALUES (3, 'Mujeres embarazadas');
INSERT INTO public."Beneficiary" (id, name) VALUES (4, 'Madres solteras');
INSERT INTO public."Beneficiary" (id, name) VALUES (5, 'Padres solteros');
INSERT INTO public."Beneficiary" (id, name) VALUES (6, 'Cuidadores/as');
INSERT INTO public."Beneficiary" (id, name) VALUES (7, 'Tutores/as');
INSERT INTO public."Beneficiary" (id, name) VALUES (8, 'Personas huérfanas');
INSERT INTO public."Beneficiary" (id, name) VALUES (9, 'Personas pertenecientes a la comunidad LGBTQ+');
INSERT INTO public."Beneficiary" (id, name) VALUES (10, 'Personas no hispanohablantes');
INSERT INTO public."Beneficiary" (id, name) VALUES (11, 'Personas afromexicanas');
INSERT INTO public."Beneficiary" (id, name) VALUES (12, 'Personas refugiadas');
INSERT INTO public."Beneficiary" (id, name) VALUES (13, 'Personas desplazadas');
INSERT INTO public."Beneficiary" (id, name) VALUES (14, 'Personas migrantes');
INSERT INTO public."Beneficiary" (id, name) VALUES (15, 'Personas víctimas de violencia');
INSERT INTO public."Beneficiary" (id, name) VALUES (16, 'Comunidades indígenas');
INSERT INTO public."Beneficiary" (id, name) VALUES (17, 'Pueblos originarios');
INSERT INTO public."Beneficiary" (id, name) VALUES (18, 'Personas con vulnerabilidad socioeconómica');
INSERT INTO public."Beneficiary" (id, name) VALUES (19, 'Personas pensionadas');
INSERT INTO public."Beneficiary" (id, name) VALUES (20, 'Personas no pensionadas');
INSERT INTO public."Beneficiary" (id, name) VALUES (21, 'Personas que padecen pobreza alimentaria (desnutrición)');
INSERT INTO public."Beneficiary" (id, name) VALUES (22, 'Personas en situación de calle');
INSERT INTO public."Beneficiary" (id, name) VALUES (23, 'Personas afectadas por desastres naturales');
INSERT INTO public."Beneficiary" (id, name) VALUES (24, 'Personas en vulnerabilidad legal');
INSERT INTO public."Beneficiary" (id, name) VALUES (25, 'Familiares de personas que fueron desaparecidas');
INSERT INTO public."Beneficiary" (id, name) VALUES (26, 'Personas liberadas');
INSERT INTO public."Beneficiary" (id, name) VALUES (27, 'Personas reinsertadas');
INSERT INTO public."Beneficiary" (id, name) VALUES (28, 'Personas primodelincuentes');
INSERT INTO public."Beneficiary" (id, name) VALUES (29, 'Personas que atraviesan procesos penales');
INSERT INTO public."Beneficiary" (id, name) VALUES (30, 'Personas privadas de su libertad');
INSERT INTO public."Beneficiary" (id, name) VALUES (31, 'Personas en situación de cárcel');
INSERT INTO public."Beneficiary" (id, name) VALUES (32, 'Personas con algún padecimiento crónico');
INSERT INTO public."Beneficiary" (id, name) VALUES (33, 'Personas con algún padecimiento crónico degenerativo');
INSERT INTO public."Beneficiary" (id, name) VALUES (34, 'Personas con enfermedades congénitas');
INSERT INTO public."Beneficiary" (id, name) VALUES (35, 'Personas con cáncer');
INSERT INTO public."Beneficiary" (id, name) VALUES (36, 'Personas con alguna enfermedad en etapa terminal');
INSERT INTO public."Beneficiary" (id, name) VALUES (37, 'Personas con vulnerabilidad emocional');
INSERT INTO public."Beneficiary" (id, name) VALUES (38, 'Personas con trastornos alimenticios');
INSERT INTO public."Beneficiary" (id, name) VALUES (39, 'Personas con trastornos psicológicos');
INSERT INTO public."Beneficiary" (id, name) VALUES (40, 'Personas con neurodivergencia');
INSERT INTO public."Beneficiary" (id, name) VALUES (41, 'Personas con discapacidad intelectual');
INSERT INTO public."Beneficiary" (id, name) VALUES (42, 'Personas con discapacidad motriz');
INSERT INTO public."Beneficiary" (id, name) VALUES (43, 'Personas con discapacidad visual');
INSERT INTO public."Beneficiary" (id, name) VALUES (44, 'Personas con discapacidad auditiva');
INSERT INTO public."Beneficiary" (id, name) VALUES (45, 'Personas con discapacidad psicosocial');
INSERT INTO public."Beneficiary" (id, name) VALUES (46, 'Personas con discapacidad para comunicarse');
INSERT INTO public."Beneficiary" (id, name) VALUES (47, 'Personas de baja estatura');
INSERT INTO public."Beneficiary" (id, name) VALUES (48, 'Personas con adicciones');
INSERT INTO public."Beneficiary" (id, name) VALUES (49, 'Personas con necesidad prehospitalaria');
INSERT INTO public."Beneficiary" (id, name) VALUES (50, 'Personas que requieren donación de órganos');
INSERT INTO public."Beneficiary" (id, name) VALUES (51, 'Personas que requieren donación de células madre');
INSERT INTO public."Beneficiary" (id, name) VALUES (52, 'Personas que requieren donación de sangre');
INSERT INTO public."Beneficiary" (id, name) VALUES (53, 'Personas que requieren donación de cabello');
INSERT INTO public."Beneficiary" (id, name) VALUES (54, 'Personal docente');
INSERT INTO public."Beneficiary" (id, name) VALUES (55, 'Estudiantes');
INSERT INTO public."Beneficiary" (id, name) VALUES (56, 'Personas analfabetismo');
INSERT INTO public."Beneficiary" (id, name) VALUES (57, 'Personas de altas capacidades intelectuales o superdotadas');
INSERT INTO public."Beneficiary" (id, name) VALUES (58, 'Investigadores');
INSERT INTO public."Beneficiary" (id, name) VALUES (59, 'Divulgadores de información');
INSERT INTO public."Beneficiary" (id, name) VALUES (60, 'Artistas');
INSERT INTO public."Beneficiary" (id, name) VALUES (61, 'Artesanos');
INSERT INTO public."Beneficiary" (id, name) VALUES (62, 'Deportistas');
INSERT INTO public."Beneficiary" (id, name) VALUES (63, 'Empleados');
INSERT INTO public."Beneficiary" (id, name) VALUES (64, 'Emprendedores');
INSERT INTO public."Beneficiary" (id, name) VALUES (65, 'Emprendimientos');
INSERT INTO public."Beneficiary" (id, name) VALUES (66, 'Personas con actividades agropecuarias');
INSERT INTO public."Beneficiary" (id, name) VALUES (67, 'Personas con actividades en la construcción');
INSERT INTO public."Beneficiary" (id, name) VALUES (68, 'Personas con actividades en la manufactura');
INSERT INTO public."Beneficiary" (id, name) VALUES (69, 'Trabajadores en situación informal');
INSERT INTO public."Beneficiary" (id, name) VALUES (70, 'Pepenadores');
INSERT INTO public."Beneficiary" (id, name) VALUES (71, 'Sectores vulnerables de la pirámide de la movilidad (ciclistas, peatones, etc)');
INSERT INTO public."Beneficiary" (id, name) VALUES (72, 'Preservación del patrimonio cultural');
INSERT INTO public."Beneficiary" (id, name) VALUES (73, 'Espacio público urbano');
INSERT INTO public."Beneficiary" (id, name) VALUES (74, 'Organizaciones de la sociedad civil');
INSERT INTO public."Beneficiary" (id, name) VALUES (75, 'Instituciones públicas (gubernamentales)');
INSERT INTO public."Beneficiary" (id, name) VALUES (76, 'Centros de capacitación');
INSERT INTO public."Beneficiary" (id, name) VALUES (77, 'Instituciones educativas');
INSERT INTO public."Beneficiary" (id, name) VALUES (78, 'Guarderías');
INSERT INTO public."Beneficiary" (id, name) VALUES (79, 'Hospitales');
INSERT INTO public."Beneficiary" (id, name) VALUES (80, 'Centro de salud');
INSERT INTO public."Beneficiary" (id, name) VALUES (81, 'Comedores');
INSERT INTO public."Beneficiary" (id, name) VALUES (82, 'Bancos de alimentos');
INSERT INTO public."Beneficiary" (id, name) VALUES (83, 'Casas de reposo');
INSERT INTO public."Beneficiary" (id, name) VALUES (84, 'Casas hogar');
INSERT INTO public."Beneficiary" (id, name) VALUES (85, 'Albergues');
INSERT INTO public."Beneficiary" (id, name) VALUES (86, 'Animales de compañía');
INSERT INTO public."Beneficiary" (id, name) VALUES (87, 'Animales exóticos');
INSERT INTO public."Beneficiary" (id, name) VALUES (88, 'Animales de campo');
INSERT INTO public."Beneficiary" (id, name) VALUES (89, 'Animales salvajes');
INSERT INTO public."Beneficiary" (id, name) VALUES (90, 'Animales en peligro de extinción');
INSERT INTO public."Beneficiary" (id, name) VALUES (91, 'Animales marinos');
INSERT INTO public."Beneficiary" (id, name) VALUES (92, 'Animales de agua dulce');
INSERT INTO public."Beneficiary" (id, name) VALUES (93, 'Ecosistemas terrestres');
INSERT INTO public."Beneficiary" (id, name) VALUES (94, 'Ecosistemas montañosos');
INSERT INTO public."Beneficiary" (id, name) VALUES (95, 'Ecosistemas marinos');
INSERT INTO public."Beneficiary" (id, name) VALUES (96, 'Ecosistemas de agua dulce');
INSERT INTO public."Beneficiary" (id, name) VALUES (97, 'Preservación del patrimonio natural urbano');
INSERT INTO public."Beneficiary" (id, name) VALUES (98, 'Reservas naturales protegidas');
INSERT INTO public."Beneficiary" (id, name) VALUES (99, 'Flora en general');
