INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (1, 'Secretaría de Seguridad', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (2, 'Secretaría General de Gobierno', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (3, 'Secretaría de Finanzas y Tesorería General del Estado', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (4, 'Secretaría Movilidad y Planeación Urbana', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (5, 'Secretaría de Medio Ambiente', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (6, 'Secretaría de Economía', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (7, 'Secretaría de Desarrollo Regional y Agropecuario', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (8, 'Secretaría de Turismo', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (9, 'Secretaría de Igualdad e Inclusión', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (10, 'Secretaría de las Mujeres', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (11, 'Secretaría de Educación', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (12, 'Secretaría de Salud', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (13, 'Secretaría de Cultura', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (14, 'Instituto de la Vivienda de Nuevo León', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (15, 'Fomento Metropolitano de Monterrey', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (16, 'Servicios de Agua y Drenaje de Monterrey', 1);
INSERT INTO public."GovernmentOrganization" (id, name, "governmentOrganizationCategoryId") VALUES (17, 'Instituto de Innovación y Transferencia de Tecnología de Nuevo León', 1);
