insert into "Beneficiary"
values (default, 'Familias'),
       (default, 'Familias monoparentales'),
       (default, 'Mujeres embarazadas'),
       (default, 'Madres solteras'),
       (default, 'Padres solteros'),
       (default, 'Cuidadores/as'),
       (default, 'Tutores/as'),
       (default, 'Personas huérfanas'),
       (default, 'Personas pertenecientes a la comunidad LGBTQ+'),
       (default, 'Personas no hispanohablantes'),
       (default, 'Personas afromexicanas'),
       (default, 'Personas refugiadas'),
       (default, 'Personas desplazadas'),
       (default, 'Personas migrantes'),
       (default, 'Personas víctimas de violencia'),
       (default, 'Comunidades indígenas'),
       (default, 'Pueblos originarios'),
       (default, 'Personas con vulnerabilidad socioeconómica'),
       (default, 'Personas pensionadas'),
       (default, 'Personas no pensionadas'),
       (default, 'Personas que padecen pobreza alimentaria (desnutrición)'),
       (default, 'Personas en situación de calle'),
       (default, 'Personas afectadas por desastres naturales'),
       (default, 'Personas en vulnerabilidad legal'),
       (default, 'Familiares de personas que fueron desaparecidas'),
       (default, 'Personas liberadas'),
       (default, 'Personas reinsertadas'),
       (default, 'Personas primodelincuentes'),
       (default, 'Personas que atraviesan procesos penales'),
       (default, 'Personas privadas de su libertad'),
       (default, 'Personas en situación de cárcel'),
       (default, 'Personas con algún padecimiento crónico'),
       (default, 'Personas con algún padecimiento crónico degenerativo'),
       (default, 'Personas con enfermedades congénitas'),
       (default, 'Personas con cáncer'),
       (default, 'Personas con alguna enfermedad en etapa terminal'),
       (default, 'Personas con vulnerabilidad emocional'),
       (default, 'Personas con trastornos alimenticios'),
       (default, 'Personas con trastornos psicológicos'),
       (default, 'Personas con neurodivergencia'),
       (default, 'Personas con discapacidad intelectual'),
       (default, 'Personas con discapacidad motriz'),
       (default, 'Personas con discapacidad visual'),
       (default, 'Personas con discapacidad auditiva'),
       (default, 'Personas con discapacidad psicosocial'),
       (default, 'Personas con discapacidad para comunicarse'),
       (default, 'Personas de baja estatura'),
       (default, 'Personas con adicciones'),
       (default, 'Personas con necesidad prehospitalaria'),
       (default, 'Personas que requieren donación de órganos'),
       (default, 'Personas que requieren donación de células madre'),
       (default, 'Personas que requieren donación de sangre'),
       (default, 'Personas que requieren donación de cabello'),
       (default, 'Personal docente'),
       (default, 'Estudiantes'),
       (default, 'Personas analfabetismo'),
       (default, 'Personas de altas capacidades intelectuales o superdotadas'),
       (default, 'Investigadores'),
       (default, 'Divulgadores de información'),
       (default, 'Artistas'),
       (default, 'Artesanos'),
       (default, 'Deportistas'),
       (default, 'Empleados'),
       (default, 'Emprendedores'),
       (default, 'Emprendimientos'),
       (default, 'Personas con actividades agropecuarias'),
       (default, 'Personas con actividades en la construcción'),
       (default, 'Personas con actividades en la manufactura'),
       (default, 'Trabajadores en situación informal'),
       (default, 'Pepenadores'),
       (default, 'Sectores vulnerables de la pirámide de la movilidad (ciclistas, peatones, etc)'),
       (default, 'Preservación del patrimonio cultural'),
       (default, 'Espacio público urbano'),
       (default, 'Organizaciones de la sociedad civil'),
       (default, 'Instituciones públicas (gubernamentales)'),
       (default, 'Centros de capacitación'),
       (default, 'Instituciones educativas'),
       (default, 'Guarderías'),
       (default, 'Hospitales'),
       (default, 'Centro de salud'),
       (default, 'Comedores'),
       (default, 'Bancos de alimentos'),
       (default, 'Casas de reposo'),
       (default, 'Casas hogar'),
       (default, 'Albergues'),
       (default, 'Animales de compañía'),
       (default, 'Animales exóticos'),
       (default, 'Animales de campo'),
       (default, 'Animales salvajes'),
       (default, 'Animales en peligro de extinción'),
       (default, 'Animales marinos'),
       (default, 'Animales de agua dulce'),
       (default, 'Ecosistemas terrestres'),
       (default, 'Ecosistemas montañosos'),
       (default, 'Ecosistemas marinos'),
       (default, 'Ecosistemas de agua dulce'),
       (default, 'Preservación del patrimonio natural urbano'),
       (default, 'Reservas naturales protegidas'),
       (default, 'Flora en general');
