INSERT INTO public."Service" (id, name, "categoryId") VALUES (1, 'Diseño de portal o intranet para gestión interna', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (2, 'Diseño de metodologías de procesos creativos (design thinking)', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (3, 'Fortalecimiento institucional', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (4, 'Transformación digital', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (5, 'Accesibilidad web (inclusión digital para personas con alguna discapacidad)', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (6, 'Conocimiento de procedimientos y estandarización', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (7, 'Conocimiento de procesos de documentación', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (8, 'Administración de proyectos', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (9, 'Conocimiento sobre marco lógico', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (10, 'Conocimiento sobre teoría del cambio', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (11, 'Creación de tu programa de voluntariado institucional para empresas', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (12, 'Manejo de software Microsoft Office (Word, Excel, Excel, etc.)', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (13, 'Herramientas de recolección de datos (minería de datos)', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (14, 'Análisis de datos (ciencia de datos)', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (15, 'Interpretación de datos', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (16, 'Metodologías de investigación', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (17, 'Generación/conocimiento de herramientas para la productividad', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (18, 'Indicadores de productividad', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (19, 'Estrategias para la escalabilidad de tus proyectos', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (20, 'Estrategias para la replicabilidad de tus proyectos', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (21, 'Conocimiento sobre buenas prácticas medioambientales', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (22, 'Conocimiento sobre gestión de residuos', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (23, 'Adaptación de tecnologías limpias', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (24, 'Conocimiento de protocolos de seguridad', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (25, 'Conocimiento de protocolos de protección civil', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (26, 'Protocolos de difusión', 1);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (27, 'Conocimiento sobre comercio electrónico', 2);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (28, 'Generación de emprendimiento social', 2);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (29, 'Industrialización de productos de la organización', 2);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (30, 'Conocimiento de comercio internacional', 2);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (31, 'Asesoría contable', 3);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (32, 'Asesoría fiscal', 3);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (33, 'Procuración de fondos', 3);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (34, 'Conocimiento sobre fuentes de financiamiento', 3);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (35, 'Conocimiento sobre crowdfunding', 3);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (36, 'Gestión de donativos en especie', 3);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (37, 'Gestión de donativos económicos', 3);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (38, 'Conocimiento de convocatorias para bajar fondos', 3);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (39, 'Software contable', 3);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (40, 'Fortalecimiento del voluntariado', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (41, 'Desarrollo de habilidades de liderazgo', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (42, 'Procesos de reclutamiento', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (43, 'Capacitación continua', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (44, 'Cursos de actualización', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (45, 'Servicios psicológicos', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (46, 'Servicios de salud', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (47, 'Diseño de programas para incentivos', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (48, 'Software para la gestión del talento', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (49, 'Conocimiento de mediación de conflictos', 4);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (50, 'Asesoría legal', 5);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (51, 'Ciberseguridad', 5);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (52, 'Servicios de notarias públicas', 5);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (53, 'Asesoría para conformación de donataria autorizada', 5);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (54, 'Temas de transparencia y anticorrupción', 5);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (55, 'Asesoría en el marco normativo de mi causa social', 5);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (56, 'Asesoría en temas de aseguradoras', 5);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (57, 'Asesoría para constitución legal', 5);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (58, 'Desarrollo de una identidad gráfica', 6);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (59, 'Diseño de página web', 6);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (60, 'Mantenimiento de página web', 6);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (61, 'Diseño de redes sociales', 6);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (62, 'Administración de redes sociales', 6);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (63, 'Diseño de estrategia de comunicación', 6);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (64, 'Diseño de estrategia de marketing', 6);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (65, 'Marketing inclusivo', 6);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (66, 'Generación de material gráfico y audiovisual', 6);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (67, 'Metodologías de diseño participativo', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (68, 'Estrategias para el acercamiento con nuevas comunidades', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (69, 'Fortalecimiento de redes de colaboración', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (70, 'Alianzas para detonar difusión de tu causa social', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (71, 'Servicio social con universidades', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (72, 'Conexión con nuevos proveedores', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (73, 'Activismo político', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (74, 'Servicios de traducción a otro idioma', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (75, 'Servicio de traducción a una lengua indígena', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (76, 'Servicio de sistema y escritura Braille', 7);
INSERT INTO public."Service" (id, name, "categoryId") VALUES (77, 'Servicio de intérprete de Lengua de Señas Mexicana', 7);
