INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (1, 'Aguascalientes', 'Ags.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (2, 'Baja California', 'BC');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (3, 'Baja California Sur', 'BCS');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (4, 'Campeche', 'Camp.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (5, 'Coahuila de Zaragoza', 'Coah.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (6, 'Colima', 'Col.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (7, 'Chiapas', 'Chis.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (8, 'Chihuahua', 'Chih.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (9, 'Ciudad de México', 'CDMX');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (10, 'Durango', 'Dgo.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (11, 'Guanajuato', 'Gto.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (12, 'Guerrero', 'Gro.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (13, 'Hidalgo', 'Hgo.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (14, 'Jalisco', 'Jal.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (15, 'México', 'Mex.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (16, 'Michoacán de Ocampo', 'Mich.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (17, 'Morelos', 'Mor.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (18, 'Nayarit', 'Nay.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (19, 'Nuevo León', 'NL');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (20, 'Oaxaca', 'Oax.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (21, 'Puebla', 'Pue.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (22, 'Querétaro', 'Qro.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (23, 'Quintana Roo', 'Q. Roo');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (24, 'San Luis Potosí', 'SLP');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (25, 'Sinaloa', 'Sin.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (26, 'Sonora', 'Son.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (27, 'Tabasco', 'Tab.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (28, 'Tamaulipas', 'Tamps.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (29, 'Tlaxcala', 'Tlax.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (30, 'Veracruz de Ignacio de la Llave', 'Ver.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (31, 'Yucatán', 'Yuc.');
INSERT INTO public."State" (id, name, "abbreviatedName") VALUES (32, 'Zacatecas', 'Zac.');
